## Import the neccessary libraries

In [29]:
import pandas as pd
import numpy as np

## Load the dataset

In [30]:
df = pd.read_csv(r"C:\Users\name\Desktop\PROJECTS\My_Projects\ghana_house_rent_project\data\house_rentals.csv")

## Inspect the dataset

In [31]:
df.head()

,url,listing_type,name,price,category,bedrooms,bathrooms,floor_area,location,condition,amenities,region,locality,parking_space,is_furnished,lat,lng
0,https://tonaton.com/a-MfYFNdCgCTytOcmvZIh0Kzrj...,rentals,"2bdrm Apartment in Charclem Ventures, East Leg...",9196,Flats,2.0,2.0,145.0,"Greater Accra, East Legon",Used,"24-hour Electricity,Air Conditioning,Balcony,C...",Greater Accra,East Legon,False,Semi-Furnished,5.635828,-0.161359
1,https://tonaton.com/a-MfYFNdCgwtb8Itol9odpMPvC...,rentals,"2bdrm Apartment in , Dzorwulu for rent",7500,Flats,2.0,2.0,100.0,"Greater Accra, Dzorwulu",Used,"24-hour Electricity,Air Conditioning,Apartment...",Greater Accra,Dzorwulu,False,Unfurnished,5.614123,-0.195647
2,https://tonaton.com/a-MfYFNdCgPjnzPYwNFEv5JrGy...,rentals,"4bdrm House in Lakeside Estate, for Rent",11200,Detached,4.0,5.0,100.0,"Greater Accra, Ashaley Botwe, Lake Side Estate",New,"Tiled Floor,Chandelier,Dining Area,Balcony,Pop...",Greater Accra,Ashaley Botwe,False,Semi-Furnished,5.680213,-0.137248
3,https://tonaton.com/a-MfYFNdCgwmXHQRNJiSR3rok8...,rentals,"3bdrm House in Ayathar Bedroom, Teshie for Rent",2500,Detached,3.0,3.0,17.0,"Greater Accra, Teshie",Used,"Pop Ceiling,Pre-Paid Meter,24-hour Electricity...",Greater Accra,Teshie,False,Semi-Furnished,5.583166,-0.104608
4,https://tonaton.com/a-MfYFNdCgn3Bcs511lKnFE19i...,rentals,"3bdrm House in Manet Viile Estate, Spintex for...",9146,Detached,3.0,3.0,160.0,"Greater Accra, Spintex",Used,"Pre-Paid Meter,Dining Area,Chandelier,Balcony,...",Greater Accra,Spintex,False,Semi-Furnished,5.637614,-0.126606

In [32]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17890 entries, 0 to 17889
Data columns (total 17 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   url            17890 non-null  object
 1   listing_type   17890 non-null  object
 2   name           17890 non-null  object
 3   price          17890 non-null  int64
 4   category       17890 non-null  object
 5   bedrooms       17890 non-null  float64
 6   bathrooms      17890 non-null  float64
 7   floor_area     17890 non-null  float64
 8   location       17890 non-null  object
 9   condition      17890 non-null  object
 10  amenities      17890 non-null  object
 11  region         17890 non-null  object
 12  locality       17890 non-null  object
 13  parking_space  17890 non-null  bool
 14  is_furnished   17890 non-null  object
 15  lat            17890 non-null  float64
 16  lng            17890 non-null  float64
dtypes: bool(1), float64(5), int64(1), object(10)
memory usage: 2.2+ MB

In [33]:
df.describe()

,price,bedrooms,bathrooms,floor_area,lat,lng
count,17890.000000,17890.000000,17890.000000,17890.000000,17890.000000,17890.000000
mean,7999.412968,2.458580,2.564561,556.094913,5.725901,-0.246623
std,10404.773528,1.262908,1.377651,1044.912578,0.454570,0.322523
min,416.000000,1.000000,1.000000,10.000000,4.849041,-2.579248
25%,1700.000000,2.000000,1.000000,100.000000,5.593759,-0.215087
50%,3500.000000,2.000000,2.000000,145.000000,5.637614,-0.161359
75%,9872.250000,3.000000,3.000000,600.000000,5.682581,-0.135459
max,59524.000000,20.000000,20.000000,5000.000000,9.410999,0.563609

## Check for missing values and duplicates

In [34]:
df.isnull().sum()

url              0
listing_type     0
name             0
price            0
category         0
bedrooms         0
bathrooms        0
floor_area       0
location         0
condition        0
amenities        0
region           0
locality         0
parking_space    0
is_furnished     0
lat              0
lng              0
dtype: int64

In [35]:
df.duplicated().sum()

np.int64(0)

The dataset is a clean one with no missing values

## Drop irrelevant columns

In [36]:
df.drop(['url','listing_type','name'],axis=1,inplace=True)

In [37]:
df.head()

,price,category,bedrooms,bathrooms,floor_area,location,condition,amenities,region,locality,parking_space,is_furnished,lat,lng
0,9196,Flats,2.0,2.0,145.0,"Greater Accra, East Legon",Used,"24-hour Electricity,Air Conditioning,Balcony,C...",Greater Accra,East Legon,False,Semi-Furnished,5.635828,-0.161359
1,7500,Flats,2.0,2.0,100.0,"Greater Accra, Dzorwulu",Used,"24-hour Electricity,Air Conditioning,Apartment...",Greater Accra,Dzorwulu,False,Unfurnished,5.614123,-0.195647
2,11200,Detached,4.0,5.0,100.0,"Greater Accra, Ashaley Botwe, Lake Side Estate",New,"Tiled Floor,Chandelier,Dining Area,Balcony,Pop...",Greater Accra,Ashaley Botwe,False,Semi-Furnished,5.680213,-0.137248
3,2500,Detached,3.0,3.0,17.0,"Greater Accra, Teshie",Used,"Pop Ceiling,Pre-Paid Meter,24-hour Electricity...",Greater Accra,Teshie,False,Semi-Furnished,5.583166,-0.104608
4,9146,Detached,3.0,3.0,160.0,"Greater Accra, Spintex",Used,"Pre-Paid Meter,Dining Area,Chandelier,Balcony,...",Greater Accra,Spintex,False,Semi-Furnished,5.637614,-0.126606

In [42]:
df.to_csv(r"C:\Users\name\Desktop\PROJECTS\My_Projects\ghana_house_rent_project\data\cleaned_house_rentals.csv",index=False)